nodes:
  - address: 192.168.44.188
    internal_address: 192.168.44.188
    user: vagrant
    ssh_agent_auth: true
    ssh_key_path: /tmp/id_rsa
    role: [controlplane, etcd, worker]
  - address: 192.168.44.189
    internal_address: 192.168.44.189
    user: vagrant
    ssh_agent_auth: true
    ssh_key_path: /tmp/id_rsa
    role: [controlplane, etcd, worker]
  - address: 192.168.44.190
    internal_address: 192.168.44.190
    user: vagrant
    ssh_agent_auth: true
    ssh_key_path: /tmp/id_rsa
    role: [controlplane, etcd, worker]

ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"

