---  
  - hosts: jump
    remote_user: kloia
    connection: local
    roles:
      - yum
      - master
    
  - hosts: servers
    remote_user: kloia
    become: true
    roles:
      - yum
      - docker
      - rke-prep
