--- 
  - name: Install EPEL repository on RHEL
    become: true
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present
    when: ansible_distribution == 'RedHat'

  - name: Add Centos Base Repo on RHEL
    become: true
    copy:
      src: files/base.repo
      dest: /etc/yum.repos.d/base.repo
    when: ansible_distribution == 'RedHat'

  - name: Install container-selinux
    become: true
    yum:
      name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm
      state: present
    
