---
- name: Get latest RKE download URL
  command : curl -s https://api.github.com/repos/rancher/rke/releases/latest
  register: rke_json

- name: Set rke_object variable
  set_fact:
    rke_object: "{{ rke_json.stdout | from_json }}"


- name: Set rke_download_url variable
  set_fact:
    rke_download_url: "{{ (rke_object.assets|selectattr('browser_download_url','contains','linux-amd64')|first).browser_download_url }}"

- name: Get RKE
  become: true
  get_url:
    url: "{{ rke_download_url }}"
    dest: /usr/local/bin/rke
    mode: a+x