---  
- hosts: jump
  connection: local
  roles:
    - jump-prep
  vars_files:
    - ../vars/general-config.yml
  
- hosts: servers
  become: true
  gather_facts: true
  roles:
    - worker-prep
    - docker
  vars_files:
    - ../vars/general-config.yml

- hosts: jump
  connection: local
  roles:
    - rke-install
    - after-install
  vars_files:
    - ../vars/general-config.yml
    - ../vars/aws-config.yml
    - ../vars/aws-secret.yml
